name: DashLord report

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["DashLord scans"]
    branches: [main]
    types:
      - completed

# allow only one concurrent report action
concurrency:
  cancel-in-progress: true
  group: report

permissions:
  contents: write

jobs:
  website:
    runs-on: ubuntu-latest
    name: Website
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/cache@v5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # build the report
      - id: dashlord-report
        uses: SocialGouv/dashlord-actions/report@20b2f87135667b379650473197967515e6ca85b8 # 1.46.1

      # to save the generated report.json as artifact
      - uses: actions/upload-artifact@v7
        with:
          path: report.json
          name: report
          if-no-files-found: error

      # save full report for history
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: '["report.json"]'
          author_name: "incubateur-ademe-admin"
          author_email: "accelerateurdelatransitionecologique@ademe.fr"
          message: "chore: report update"

      # deploy build to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # 4.8.0
        with:
          branch: gh-pages
          folder: build
